version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: web_laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel
    db:
        image: mysql:8.0
        container_name: web_laravel_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ecomm
            MYSQL_ROOT_PASSWORD: pass
            MYSQL_PASSWORD: pass
            MYSQL_USER: laravel_user
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel
    nginx:
        image: nginx:alpine
        container_name: web_laravel_nginx
        restart: unless-stopped
        ports:
            - "1629:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
volumes:
    dbdata: